### ISSUE TITLE
include/exclude options

### ISSUE THREAD

**Issue by whizz-shumphrey** [sebastian-software/rollup-plugin-rebase#20] opened 2019-03-25 12:39 UTC
Hi,

I'm trying to exclude SVGs from rebase as I have another plugin that inlines them, however I'm still getting the SVGs rebasing.

I've tried setting the exclude, but they still get copied. I've also tried setting the include to the specific filetypes (mp3 in my case) and this also has issues as no files are then rebased.

This is in my rollup.config.js

rebasePlugin({
      exclude: "**/*.svg",
      verbose: true
    }),

**Comment by swernerx** [comment] 2019-03-25 12:46
Thanks for reporting. Sounds like a valid requirement. Can you share a mini project for reproducing the issue? Thanks!

**Comment by sami616** [comment] 2019-08-12 11:11
Also experiencing this, need to exclude svgs because i want them injected inline.

**Comment by sami616** [comment] 2020-03-19 08:22
Checking in to find out, is there a plan to fix this? do you need someone to open a PR?

**Comment by zackphilipps** [comment] 2020-03-24 21:06
@whizz-shumphrey are you on Windows by chance?

**Comment by sami616** [comment] 2020-03-24 21:22
I'm on Mac here

**Comment by whizz-shumphrey** [comment] 2020-03-24 21:40
Mac also

**Comment by zackphilipps** [comment] 2020-03-24 22:37
@whizz-shumphrey @sami616 do you want to try:

1. Clone from my fork
2. Run `npm pack`
3. Install the .tgz file in your project by running `npm install full/path/to/tarball.tgz` to see if it works?

**Comment by zackphilipps** [comment] 2020-03-24 22:56
Here's a link: https://github.com/zackphilipps/rollup-plugin-rebase

**Comment by sami616** [comment] 2020-03-27 10:09
@zackphilipps yes! `exclude` now works in my project allowing me to handle svg's differently. Will this be merged into master? 

```js
 plugins: [
    // Handle typescript
    typescript({
      typescript: require('typescript'),
      exclude: ['**/*.stories.tsx', 'node_modules'],
    }),
    // Handle all assets
    rebasePlugin({
      exclude: ['**/*.svg'],
    }),
    svg(),
  ],
```

**Comment by zackphilipps** [comment] 2020-03-27 16:01
@swernerx ^^

**Comment by zackphilipps** [comment] 2020-03-30 22:09
@sami616 @whizz-shumphrey my PR was merged into master.

**Comment by swernerx** [comment] 2020-03-31 09:25
This is now released as v3.3.0. Can you share whether this version is working correctly for you?

**Comment by swernerx** [comment] 2020-03-31 10:13
Closing this for now. Please re-open if there is still an issue.

**Closed by swernerx** 2020-03-31 10:13 UTC

**Comment by zackphilipps** [comment] 2020-04-10 19:33
@swernerx v3.3.3 worked for me. Thanks!
